// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/labstack/echo/v4"
	"github.com/thedivinez/go-libs/gothex"
	"github.com/thedivinez/pocketvault.ai/components/dashboard"
	"github.com/thedivinez/pocketvault.ai/types"
)

func HandleChangePassword(c echo.Context) error {
	// if session, authenticated := router.GetAuthSession(c); authenticated {
	// 	var user types.User
	// 	json.Unmarshal(session.Values["user"].([]byte), &user)
	// 	return gothex.Render(c, pages.Home, user)
	// }
	// return c.Redirect(http.StatusPermanentRedirect, "/signin")
	return gothex.Render(c, ChangePassword, &types.User{Name: "Divine Zvenyika"})
}

func ChangePassword(c context.Context, data ...any) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"d-flex flex-wrap\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dashboard.SideBar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"dashboard-wrapper\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dashboard.Navbar(data[0].(*types.User)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\" dashboard-container \"><div class=\"dashboard-inner\"><div class=\"mb-4\"><h3 class=\"mb-2\">Change Password</h3></div><div class=\"card custom--card\"><div class=\"card-body\"><form method=\"post\"><input type=\"hidden\" name=\"_token\" value=\"oAdKrCRp5VaOQ0jHComz0i1IxvmD4R8RgjDiPxl7\" autocomplete=\"off\"><div class=\"form-group\"><label class=\"form-label required\" for=\"current_password\">Current Password</label> <input type=\"password\" class=\"form-control form--control\" name=\"current_password\" required=\"\" autocomplete=\"current-password\" id=\"current_password\"></div><div class=\"form-group\"><label class=\"form-label required\" for=\"password\">Password</label> <input type=\"password\" class=\"form-control form--control \" name=\"password\" required=\"\" autocomplete=\"current-password\" id=\"password\"></div><div class=\"form-group\"><label class=\"form-label required\" for=\"password_confirmation\">Confirm Password</label> <input type=\"password\" class=\"form-control form--control\" name=\"password_confirmation\" required=\"\" autocomplete=\"current-password\" id=\"password_confirmation\"></div><div class=\"form-group mt-3\"><button type=\"submit\" class=\"btn btn--base w-100\">Submit</button></div></form></div></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = App(c).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
