// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/labstack/echo/v4"
	"github.com/thedivinez/go-libs/gothex"
	"github.com/thedivinez/pocketvault.ai/components/dashboard"
	"github.com/thedivinez/pocketvault.ai/types"
)

func HandleDepositHistory(c echo.Context) error {
	// if session, authenticated := router.GetAuthSession(c); authenticated {
	// 	var user types.User
	// 	json.Unmarshal(session.Values["user"].([]byte), &user)
	// 	return gothex.Render(c, pages.Home, user)
	// }
	// return c.Redirect(http.StatusPermanentRedirect, "/signin")
	return gothex.Render(c, DepositHistory, &types.User{Name: "Divine Zvenyika"})
}

func DepositHistory(c context.Context, data ...any) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"d-flex flex-wrap\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dashboard.SideBar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"dashboard-wrapper\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dashboard.Navbar(data[0].(*types.User)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\" dashboard-container \"><div class=\"dashboard-inner\"><div class=\"mb-4\"><div class=\"d-flex justify-content-between\"><h3 class=\"mb-2\">Deposit History</h3><span><a href=\"/deposit\" class=\"btn btn--secondary btn--smd\">Deposit Now <i class=\"las la-long-arrow-alt-right\"></i></a></span></div></div><div class=\"accordion table--acordion\" id=\"transactionAccordion\"><div class=\"accordion-body text-center bg-white\"><h4 class=\"text--muted\"><i class=\"far fa-frown\"></i> Data not found</h4></div></div></div><div id=\"detailModal\" class=\"modal\" tabindex=\"-1\" role=\"dialog\"><div class=\"modal-dialog modal-dialog-centered\" role=\"document\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">Details</h5><span type=\"button\" class=\"close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"><i class=\"las la-times\"></i></span></div><div class=\"modal-body\"><ul class=\"list-group userData mb-2\"></ul><div class=\"feedback\"></div></div><div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-dark btn--sm\" data-bs-dismiss=\"modal\">Close</button></div></div></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = App(c).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
