// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/labstack/echo/v4"
	"github.com/thedivinez/go-libs/gothex"
	"github.com/thedivinez/pocketvault.ai/types"
)

func HandleResetPassword(c echo.Context) error {
	// if session, authenticated := router.GetAuthSession(c); authenticated {
	// 	var user types.User
	// 	json.Unmarshal(session.Values["user"].([]byte), &user)
	// 	return gothex.Render(c, pages.Home, user)
	// }
	// return c.Redirect(http.StatusPermanentRedirect, "/signin")
	return gothex.Render(c, ResetPassword, &types.User{Name: "Divine Zvenyika"})
}

func ResetPassword(c context.Context, options ...any) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"account-section position-relative\"><div class=\"container\"><div class=\"row justify-content-center\"><div class=\"col-xl-6 col-lg-7 col-md-8\"><div class=\"text-center\"><a href=\"https://prestigewealthinvest.com\" class=\"d-block mb-3 mb-sm-4 auth-page-logo\"><img src=\"/images/logo_dark.png\" alt=\"logo\"></a></div><form action=\"https://prestigewealthinvest.com/user/password/email\" method=\"POST\" class=\"account-form verify-gcaptcha\"><input type=\"hidden\" name=\"_token\" value=\"NKTglVxyknUUeRQm9u6fvLbxEFJvFPrMMpSD2fCH\" autocomplete=\"off\"><div class=\"mb-4\"><h4 class=\"mb-2\">Account Recovery</h4><p>To recover your account please provide your email or username to find your account.</p></div><div class=\"row gy-2 gap-2\"><div class=\"col-12\"><div class=\"form-group\"><label>Email or Username</label> <input type=\"text\" class=\"form-control form--control h-45\" name=\"value\" value=\"\" required autofocus=\"off\"></div></div><div class=\"col-12\"><button type=\"submit\" class=\"btn btn--base w-100\">Submit</button></div></div></form></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = App(c).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
